### ISSUE TITLE
 Cases_per_100K value probably off by a couple decimal places

### ISSUE THREAD

**Issue by ercbk** [cmu-delphi/covidcast#16]
The MSA is Michigan City - LaPorte, cbsa/geo_value = 33140, source = "indicator-combination",  signal = "confirmed_7dav_incidence_prop"  

Aug 1st value = 812.385598. It's been around 8 or 9 recently, so I'm guessing this should be 8.12385598, but would like to confirm.

**Comment by capnrefsmmat** [comment]
This is due to our source, USAFacts, reporting 6,176 cases in LaPorte County on August 1: https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/state/indiana/county/laporte-county

I was not able to identify an official source (from the county or state of Indiana) showing that spike in cases, so I'm not sure of the cause. Typically spikes like this happen when a backlog of cases is suddenly reported or an agency changes their reporting criteria, but there's no indication of what happened in this case.

**Comment by capnrefsmmat** [comment]
I'm also not sure how one reports suspicious numbers to USAFacts, since unlike JHU they don't have a convenient GitHub to report issues to...

**Comment by capnrefsmmat** [comment]
p.s. nice dashboard! But I should note that our Combined indicator does not yet include hospital admissions or SafeGraph data, since we have not yet worked to incorporate them. That should be documented on the indicator page in the API. It's not clear how to incorporate SafeGraph mobility data, and the hospital admissions data is available in only a fraction of MSAs, so it hasn't been included yet.

**Comment by ercbk** [comment]
NY Times and Indiana Data Hub don't have anything near that. From Aug 1, the 7-day total from those sources is 74 and 82 respectively. So I think this is a USAFacts issue.  

Also, thank you! And oof! I remember reading that now. I'll correct the dashboard description. Thanks for catching that.

**Comment by ercbk** [comment]
This will affect values over the next week, so is this something that could be corrected in the next batch of data from them or does somebody need to email them (info@usafacts.org)?

**Comment by capnrefsmmat** [comment]
Looking at the [LaPorte County page on USAFacts](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/state/indiana/county/laporte-county), it seems they "canceled out" the massive spike by reporting negative 6,165 cases on August 2nd. Their downloadable CSV file has been corrected to show no spike at all, and our data matches accordingly:

```
> covidcast_signal("usa-facts", "confirmed_incidence_num", geo_type="msa", geo_values="33140", start_day="2020-07-30")

A `covidcast_signal` data frame with 5 rows and 10 columns.

signals     : usa-facts:confirmed_incidence_num
geo_type    : msa

  geo_value time_value direction      issue lag value stderr sample_size
1     33140 2020-07-30        NA 2020-08-04   5    17     NA          NA
2     33140 2020-07-31        NA 2020-08-04   4    42     NA          NA
3     33140 2020-08-01        NA 2020-08-04   3     0     NA          NA
4     33140 2020-08-02        NA 2020-08-04   2     0     NA          NA
5     33140 2020-08-03        NA 2020-08-04   1     9     NA          NA
```

However, the 7-day average still shows a spike, perhaps because we don't correctly run the 7-day average again when the underlying signal is updated. I'll ping our team to see if that is possible.

**Comment by capnrefsmmat** [comment]
The signal has now been fixed by recalculating the 7-day averages. We're also working on automatically recalculating 7-day averages whenever the underlying data is updated.

```
> covidcast_signal("indicator-combination", "confirmed_7dav_incidence_num", geo_type="msa", geo_values="33140", start_day="2020-07-30")

A `covidcast_signal` data frame with 7 rows and 10 columns.

signals     : indicator-combination:confirmed_7dav_incidence_num
geo_type    : msa

  geo_value time_value direction      issue lag    value stderr sample_size
1     33140 2020-07-30        NA 2020-07-31   1 10.28571     NA          NA
2     33140 2020-07-31        NA 2020-08-04   4 13.28571     NA          NA
3     33140 2020-08-01        NA 2020-08-06   5 12.00000     NA          NA
4     33140 2020-08-02        NA 2020-08-03   1 11.14286     NA          NA
5     33140 2020-08-03        NA 2020-08-04   1 11.14286     NA          NA
6     33140 2020-08-04        NA 2020-08-05   1 10.42857     NA          NA
7     33140 2020-08-05        NA 2020-08-06   1 11.42857     NA          NA
```

**Comment by ercbk** [comment]
Awesome. Thanks, Alex
